version: '3'
services:
  ku-tech-admin:
    image: techcamp-openevent2-app:latest
    ports:
      - "9017:3000"
    
    deploy:
      replicas: 1
    restart: unless-stopped

    environment:
      NODE_ENV: production