version: '3'
services:
  ku-tech-admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9016:3000"
    
    deploy:
      replicas: 1
    restart: unless-stopped
    
    environment:
      NODE_ENV: production