version: '3'
services:
  app:
    image: parwer/ku-jobfair:latest
    ports:
      - "9069:3000"
    
    deploy:
      replicas: 1
    restart: unless-stopped

    environment:
      NODE_ENV: production